import React from 'react'
import './globals.scss'
import '@/view/scss/reset.scss'
import type { Metadata } from 'next'

import { Inter } from 'next/font/google'
import ReduxProvider from '@/repository/provider/reduxProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  )
}

export default RootLayout
